fixed actions

diff --git a/.github/workflows/node_web_app_deploy.yaml b/.github/workflows/node_web_app_deploy.yaml
--- a/.github/workflows/node_web_app_deploy.yaml
+++ b/.github/workflows/node_web_app_deploy.yaml
@@ -1,8 +1,8 @@
 on:
   workflow_call:
     inputs:
-      app_folder:
-        description: The folder of the java app.
+      workspace_name:
+        description: The name of the workspace to create the artifact for.
         type: string
         required: true
       environment:
@@ -44,26 +44,75 @@ jobs:
   build:
     name: Build Artifact
     runs-on: ubuntu-latest
+    env:
+      WORKSPACE: ${{ inputs.workspace_name }}
 
     steps:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         name: Checkout
-        with: 
-          submodules: 'true'
 
-      - name: Set up Maven Central Repository
-        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
+      - name: Prune
+        run: npx turbo@2 prune --scope ${{ env.WORKSPACE }}
+
+      - name: Enable Corepack
+        run: corepack enable
+
+      - name: Setup Node.js
+        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
         with:
-          java-version: '17'
-          distribution: 'temurin'
+          node-version-file: ".node-version"
+          cache: "yarn"
+          cache-dependency-path: "./out/yarn.lock"
+
+      - name: Install dependencies
+        run: yarn install --immutable
+        working-directory: ./out
+
+      - name: Build
+        run: yarn build
+        working-directory: ./out
 
       - name: Build the artifact
         id: make-artifact
+        env:
+          # we fall back to node-moules, even in case pnp is configured, in order to avoid bundling dependendencies
+          YARN_NODE_LINKER: node-modules
+          YARN_NM_HOISTING_LIMITS: workspaces
         run: |
-          mvn package -DskipTests
-          cp $(find ./target -maxdepth 1 -name "*.jar") ./$BUNDLE_NAME.jar
-          echo "artifact-path=$(realpath $BUNDLE_NAME.jar)" >> "$GITHUB_OUTPUT"
-        working-directory: ./${{ inputs.app_folder }}
+          set -e
+
+          # determine the entry point file name from package.json main property
+          ENTRY_POINT=$(jq -r '.main' package.json)
+
+          if [ -z $ENTRY_POINT ]; then
+            echo "::error::invalid target"
+            exit 1
+          fi
+
+          # generate node_modules folder excluding devDependencies
+          yarn workspaces focus --production
+
+          FORMAT=$(jq -r 'if .type == "module" then "esm" else "cjs" end' package.json)
+          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
+
+          mkdir ${{ github.run_id }}
+
+          # bundle compiled code, excluding node_modules
+          curl -fsSL https://esbuild.github.io/dl/v0.21.5 | sh
+          ./esbuild index=$ENTRY_POINT --bundle --format=$FORMAT --platform=node --target=node20 --packages=external --outdir=${{ github.run_id }} --allow-overwrite
+
+          # create a new package.json file, with the updated entry point
+          jq --arg sha "+$SHORT_SHA" '{"name": .name, "version": (.version + $sha), "main": "index.js", "type": (if has("type") then .type else "commonjs" end), "dependencies": .dependencies}' package.json > ${{ github.run_id }}/package.json
+
+          DEFAULT_FILES='"host.json"'
+          FILES=$(jq -r --arg default "$DEFAULT_FILES" 'if has("files") then .files else [$default] end | join(" ")' package.json)
+
+          # create the artifact (zip) with node_modules, index.js and package.json
+          zip -r $BUNDLE_NAME.zip node_modules $FILES
+          zip -ju $BUNDLE_NAME.zip ${{ github.run_id }}/index.js ${{ github.run_id }}/package.json
+
+          echo "artifact-path=$(realpath $BUNDLE_NAME.zip)" >> "$GITHUB_OUTPUT"
+        working-directory: ./out/apps/${{ inputs.workspace_name }}
 
       - name: Upload Artifact
         uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
@@ -78,7 +127,7 @@ jobs:
     if: ${{ !github.event.act }}
     needs: [build]
     runs-on: ${{ inputs.use_labels && inputs.use_private_agent && inputs.environment || inputs.use_private_agent && 'self-hosted' || 'ubuntu-latest' }}    
-    environment: pe-app-${{ inputs.environment }}-cd
+    environment: ${{ inputs.environment }}-cd
     permissions:
       id-token: write
       contents: read
@@ -90,7 +139,7 @@ jobs:
           name: ${{ env.BUNDLE_NAME }}
 
       - name: Azure Login
-        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2
+        uses: azure/login@v2 # v2.0.0
         env:
           ARM_USE_OIDC: true
         with:
@@ -104,8 +153,8 @@ jobs:
           az webapp deploy \
            --resource-group ${{ inputs.resource_group_name }} \
            --name ${{ inputs.web_app_name }} \
-           --src-path ./${{ env.BUNDLE_NAME }}.jar \
-           --type jar \
+           --src-path  ${{ env.BUNDLE_NAME }}.zip \
+           --type zip \
            --async false
 
       - name: Deploy to Staging Slot
@@ -115,8 +164,8 @@ jobs:
            --resource-group ${{ inputs.resource_group_name }} \
            --name ${{ inputs.web_app_name }} \
            --slot staging \
-           --src-path ./${{ env.BUNDLE_NAME }}.jar \
-           --type jar \
+           --src-path  ${{ env.BUNDLE_NAME }}.zip \
+           --type zip \
            --async false
 
       - name: Swap Staging and Production Slots
